AllCops:
  Exclude:
    - 'vendor/**/*'
    - '*.gemspec'

Metrics/LineLength:
  Max: 80

Metrics/MethodLength:
  Max: 16

Style/Documentation:
  Enabled: false

Style/FirstParameterIndentation:
  Enabled: false

Style/GuardClause:
  MinBodyLength: 4

Style/HashSyntax:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/IndentHash:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/UnneededPercentQ:
  Enabled: false
